version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  lint-code:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            make install-hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

workflows:
  default:
    jobs:
      - lint-code
      - aws-ecr/build_and_push_image:
          requires:
            - lint-code
          # aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
          # aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
          # region: "${AWS_REGION}"
          path: .
          repo: 'udacity-cloud-devops-capstone-project-repo'
